name: Build, Push and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: timtech4u/order-app:latest

    - name: Login to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA }}'

    - name: Deploy to CloudRun
      run: |
        gcloud run deploy order-app --region europe-west1 --image timtech4u/order-app --platform managed --allow-unauthenticated --project ${{ secrets.GCP_PROJECT_ID }}
        
